version: '3.1'

volumes:
  db_data:

services:
  redis:
    container_name: redis_${REDIS_VERSION:-latest}
    restart: always
    image: redis:${REDIS_VERSION:-latest}
    volumes:
      - db_data:/data
    ports:
      - ${REDIS_PORT:-6379}:6379
  redisCommander:
    container_name: redis_commander_${REDIS_VERSION:-latest}
    restart: always
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - ${REDIS_COMMANDER_PORT:-8081}:8081