version: '3.1'

volumes:
  db_data: {}

services:
  redis:
    container_name: flask_redis
    restart: always
    image: redis:5
    volumes:
      - db_data:/data
    ports:
      - 6379:6379
  redisCommander:
    container_name: flask_redis_commander
    restart: always
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - 8081:8081